import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import "./globals-responsive.css";
import Navbar from "@/app/ui/navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children, i
}: Readonly<{
  children: React.ReactNode;
  i: string;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Navbar i={i}/>
        {children}
      </body>
    </html>
  );
}
